-- Hand-written, not generated by drizzle-kit push: the same upstream
-- introspection bug documented in 0001_add_assets_and_sync_runs.sql
-- (drizzle-team/drizzle-orm#4496) reproduces against this database for any
-- new table with a foreign key. Applied via `npm run apply-migration`.
--
-- Conventions (column types, FK constraint naming, index naming) verified
-- against the real `positions` table via information_schema/pg_constraint,
-- since that's the closest existing analog: a child table keyed by
-- account_id with a unique (account_id, symbol) index.
CREATE TABLE "public"."watchlist_items" (
  "id" uuid PRIMARY KEY NOT NULL DEFAULT gen_random_uuid(),
  "account_id" uuid NOT NULL,
  "symbol" text NOT NULL,
  "created_at" timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "watchlist_items_account_id_accounts_id_fk" FOREIGN KEY ("account_id") REFERENCES "public"."accounts"("id")
);

CREATE UNIQUE INDEX "watchlist_items_account_symbol_idx" ON "public"."watchlist_items" USING btree ("account_id", "symbol");
