// The autonomous bot's scanning universe - liquid, actively-traded NYSE/
// NASDAQ common stocks, curated from the real synced assets table
// (lib/db/assets.ts), not hand-typed. This replaces the earlier
// 12-symbol placeholder (a reuse of Discover's Popular list) - the design
// proposal always called for "a few hundred liquid names," and hand-
// curating that many by eye was the explicit, named gap left for later.
// See STATE.md for the historical-scan result this expansion was built to
// enable, and scripts/curate-bot-watchlist.ts for how to regenerate this
// list (e.g. after the next annual S&P 500 / Nasdaq-100 reconstitution).
//
// Curation method, run once and reviewed by hand, not derived live on
// every bot cycle:
//   1. A real, independent liquidity/legitimacy reference: the union of
//      S&P 500 and Nasdaq-100 constituents (518 unique tickers), snapshotted
//      in scripts/data/index-reference-tickers.json with its own source
//      URLs and fetch date. Index membership is a real, externally-audited
//      signal for "large, liquid, real operating company" that this app has
//      no equivalent field for on its own (Alpaca's assets endpoint carries
//      no volume/market-cap data at all).
//   2. Intersected with the real synced assets table, requiring
//      tradable = true and exchange in (NYSE, NASDAQ) - both already real
//      columns on that table, not a new sync requirement. This is what
//      does the actual liquidity/legitimacy filtering; only 1 of the 518
//      reference tickers failed it (CBOE, which trades on BATS, not
//      NYSE/NASDAQ).
//   3. Cross-checked against lib/market/fund-name.ts's
//      isLikelyFundOrDerivativeName as a defense-in-depth review flag, not
//      an automatic filter - index membership already excludes virtually
//      all funds/ETFs by construction, so a match here means "look at this
//      one," not "drop it". All 8 real matches this round (ARM/PDD - ADS-
//      listed foreign companies; IVZ - Invesco itself, a real asset manager,
//      not one of its own funds; NTRS/CPT/ESS/FRT/DLR - real banks/REITs
//      whose legal name happens to contain "Trust") were confirmed false
//      positives and kept, not one was a genuine fund that slipped through.
//
// Result: 517 symbols (503 S&P 500 + 102 Nasdaq-100, deduplicated to 518
// unique tickers, minus CBOE). See the cost/performance verification and
// historical rule-rarity re-scan in STATE.md before this was shipped.
export type BotWatchlistSymbol = {
  symbol: string;
  name: string;
};

export const BOT_WATCHLIST: readonly BotWatchlistSymbol[] = [
  { symbol: "A", name: "Agilent Technologies Inc." },
  { symbol: "AAPL", name: "Apple Inc. Common Stock" },
  { symbol: "ABBV", name: "ABBVIE INC." },
  { symbol: "ABNB", name: "Airbnb, Inc. Class A Common Stock" },
  { symbol: "ABT", name: "Abbott Laboratories" },
  { symbol: "ACGL", name: "Arch Capital Group Ltd. Common Stock" },
  { symbol: "ACN", name: "Accenture PLC" },
  { symbol: "ADBE", name: "Adobe Inc. Common Stock" },
  { symbol: "ADI", name: "Analog Devices, Inc. Common Stock" },
  { symbol: "ADM", name: "Archer Daniels Midland Company" },
  { symbol: "ADP", name: "Automatic Data Processing, Inc. Common Stock" },
  { symbol: "ADSK", name: "Autodesk, Inc. Common Stock" },
  { symbol: "AEE", name: "Ameren Corporation" },
  { symbol: "AEP", name: "American Electric Power Company, Inc. Common Stock" },
  { symbol: "AES", name: "AES Corporation" },
  { symbol: "AFL", name: "Aflac Inc." },
  { symbol: "AIG", name: "American International Group, Inc." },
  { symbol: "AIZ", name: "Assurant, Inc." },
  { symbol: "AJG", name: "Arthur J. Gallagher & Co." },
  { symbol: "AKAM", name: "Akamai Technologies, Inc. Common Stock" },
  { symbol: "ALAB", name: "Astera Labs, Inc. Common Stock" },
  { symbol: "ALB", name: "Albemarle Corporation" },
  { symbol: "ALGN", name: "Align Technology, Inc. Common Stock" },
  { symbol: "ALL", name: "The Allstate Corporation" },
  { symbol: "ALLE", name: "Allegion Public Limited Company" },
  { symbol: "ALNY", name: "Alnylam Pharmaceuticals, Inc. Common Stock" },
  { symbol: "AMAT", name: "Applied Materials, Inc. Common Stock" },
  { symbol: "AMCR", name: "Amcor plc Ordinary Shares" },
  { symbol: "AMD", name: "Advanced Micro Devices, Inc. Common Stock" },
  { symbol: "AME", name: "Ametek, Inc." },
  { symbol: "AMGN", name: "Amgen Inc. Common Stock" },
  { symbol: "AMP", name: "Ameriprise Financial, Inc." },
  { symbol: "AMT", name: "American Tower Corporation" },
  { symbol: "AMZN", name: "Amazon.com, Inc. Common Stock" },
  { symbol: "ANET", name: "Arista Networks" },
  { symbol: "AON", name: "Aon plc Class A" },
  { symbol: "AOS", name: "A.O. Smith Corporation" },
  { symbol: "APA", name: "APA Corporation Common Stock" },
  { symbol: "APD", name: "Air Products & Chemicals, Inc." },
  { symbol: "APH", name: "Amphenol Corporation" },
  { symbol: "APO", name: "Apollo Global Management, Inc." },
  { symbol: "APP", name: "Applovin Corporation Class A Common Stock" },
  { symbol: "APTV", name: "Aptiv PLC" },
  { symbol: "ARE", name: "Alexandria Real Estate Equities, Inc." },
  { symbol: "ARES", name: "Ares Management Corporation Class A Common Stock" },
  { symbol: "ARM", name: "Arm Holdings plc American Depositary Shares" },
  { symbol: "ASML", name: "ASML Holding N.V. New York Registry Shares" },
  { symbol: "ATO", name: "Atmos Energy Corporation" },
  { symbol: "AVB", name: "AvalonBay Communities, Inc." },
  { symbol: "AVGO", name: "Broadcom Inc. Common Stock" },
  { symbol: "AVY", name: "Avery Dennison Corp." },
  { symbol: "AWK", name: "American Water Works Company, Inc" },
  { symbol: "AXON", name: "Axon Enterprise, Inc. Common Stock" },
  { symbol: "AXP", name: "American Express Company" },
  { symbol: "AZO", name: "AutoZone, Inc." },
  { symbol: "BA", name: "Boeing Company" },
  { symbol: "BAC", name: "Bank of America Corporation" },
  { symbol: "BALL", name: "Ball Corporation" },
  { symbol: "BAX", name: "Baxter International Inc." },
  { symbol: "BBY", name: "Best Buy Company, Inc." },
  { symbol: "BDX", name: "Becton, Dickinson and Co." },
  { symbol: "BEN", name: "Franklin Resources, Inc." },
  { symbol: "BF.B", name: "Brown-Forman Corporation Class B" },
  { symbol: "BG", name: "Bunge Global SA" },
  { symbol: "BIIB", name: "Biogen Inc. Common Stock" },
  { symbol: "BKNG", name: "Booking Holdings Inc. Common Stock" },
  { symbol: "BKR", name: "Baker Hughes Company Class A Common Stock" },
  { symbol: "BLDR", name: "Builders FirstSource, Inc." },
  { symbol: "BLK", name: "Blackrock, Inc." },
  { symbol: "BMY", name: "Bristol-Myers Squibb Co." },
  { symbol: "BNY", name: "Bank of New York Mellon Corporation" },
  { symbol: "BR", name: "Broadridge Financial Solutions Inc" },
  { symbol: "BRK.B", name: "BERKSHIRE HATHAWAY Class B" },
  { symbol: "BRO", name: "Brown & Brown, Inc." },
  { symbol: "BSX", name: "Boston Scientific Corp." },
  { symbol: "BX", name: "Blackstone Inc." },
  { symbol: "BXP", name: "BXP, Inc." },
  { symbol: "C", name: "Citigroup Inc." },
  { symbol: "CAH", name: "Cardinal Health, Inc." },
  { symbol: "CARR", name: "Carrier Global Corporation" },
  { symbol: "CASY", name: "Casey's General Stores, Inc. Common Stock" },
  { symbol: "CAT", name: "Caterpillar Inc." },
  { symbol: "CB", name: "Chubb Limited" },
  { symbol: "CBRE", name: "CBRE GROUP, INC." },
  { symbol: "CCEP", name: "Coca-Cola Europacific Partners plc Ordinary Shares" },
  { symbol: "CCI", name: "Crown Castle Inc." },
  { symbol: "CCL", name: "Carnival Corporation Ltd." },
  { symbol: "CDNS", name: "Cadence Design Systems, Inc. Common Stock" },
  { symbol: "CDW", name: "CDW Corporation Common Stock" },
  { symbol: "CEG", name: "Constellation Energy Corporation Common Stock" },
  { symbol: "CF", name: "CF Industries Holding, Inc." },
  { symbol: "CFG", name: "Citizens Financial Group, Inc." },
  { symbol: "CHD", name: "Church & Dwight Co., Inc." },
  { symbol: "CHRW", name: "C.H. Robinson Worldwide, Inc. Common Stock" },
  { symbol: "CHTR", name: "Charter Communications, Inc. Class A Common Stock New" },
  { symbol: "CI", name: "The Cigna Group" },
  { symbol: "CIEN", name: "Ciena Corporation" },
  { symbol: "CINF", name: "Cincinnati Financial Corporation Common Stock" },
  { symbol: "CL", name: "Colgate-Palmolive Company" },
  { symbol: "CLX", name: "Clorox Company" },
  { symbol: "CMCSA", name: "Comcast Corporation Class A Common Stock" },
  { symbol: "CME", name: "CME Group Inc. Class A Common Stock" },
  { symbol: "CMG", name: "Chipotle Mexican Grill, Inc." },
  { symbol: "CMI", name: "Cummins Inc." },
  { symbol: "CMS", name: "CMS Energy Corporation" },
  { symbol: "CNC", name: "Centene Corporation" },
  { symbol: "CNP", name: "CenterPoint Energy, Inc." },
  { symbol: "COF", name: "Capital One Financial" },
  { symbol: "COHR", name: "Coherent Corp." },
  { symbol: "COIN", name: "Coinbase Global, Inc. Class A Common Stock" },
  { symbol: "COO", name: "The Cooper Companies, Inc. Common Stock" },
  { symbol: "COP", name: "ConocoPhillips" },
  { symbol: "COR", name: "Cencora, Inc." },
  { symbol: "COST", name: "Costco Wholesale Corporation Common Stock" },
  { symbol: "CPAY", name: "Corpay, Inc." },
  { symbol: "CPRT", name: "Copart, Inc. (DE) Common Stock" },
  { symbol: "CPT", name: "Camden Property Trust" },
  { symbol: "CRH", name: "CRH Public Limited Company" },
  { symbol: "CRL", name: "Charles River Laboratories International, Inc." },
  { symbol: "CRM", name: "Salesforce, Inc." },
  { symbol: "CRWD", name: "CrowdStrike Holdings, Inc. Class A Common Stock" },
  { symbol: "CRWV", name: "CoreWeave, Inc. Class A Common Stock" },
  { symbol: "CSCO", name: "Cisco Systems, Inc. Common Stock (DE)" },
  { symbol: "CSGP", name: "CoStar Group, Inc. Common Stock" },
  { symbol: "CSX", name: "CSX Corporation Common Stock" },
  { symbol: "CTAS", name: "Cintas Corporation Common Stock" },
  { symbol: "CTSH", name: "Cognizant Technology Solutions Corporation Class A Common Stock" },
  { symbol: "CTVA", name: "Corteva, Inc. Common Stock" },
  { symbol: "CVNA", name: "Carvana Co." },
  { symbol: "CVS", name: "CVS HEALTH CORPORATION" },
  { symbol: "CVX", name: "Chevron Corporation" },
  { symbol: "D", name: "Dominion Energy, Inc Common Stock" },
  { symbol: "DAL", name: "Delta Air Lines, Inc." },
  { symbol: "DASH", name: "DoorDash, Inc. Class A Common Stock" },
  { symbol: "DD", name: "DuPont de Nemours, Inc. Common Stock" },
  { symbol: "DDOG", name: "Datadog, Inc. Class A Common Stock" },
  { symbol: "DE", name: "Deere & Company" },
  { symbol: "DECK", name: "Deckers Outdoor Corp" },
  { symbol: "DELL", name: "Dell Technologies Inc." },
  { symbol: "DG", name: "Dollar General Corp." },
  { symbol: "DGX", name: "Quest Diagnostics Inc." },
  { symbol: "DHI", name: "D.R. Horton Inc." },
  { symbol: "DHR", name: "Danaher Corporation" },
  { symbol: "DIS", name: "The Walt Disney Company" },
  { symbol: "DLR", name: "Digital Realty Trust, Inc." },
  { symbol: "DLTR", name: "Dollar Tree Inc. Common Stock" },
  { symbol: "DOC", name: "Healthpeak Properties, Inc." },
  { symbol: "DOV", name: "Dover Corporation" },
  { symbol: "DOW", name: "Dow Inc." },
  { symbol: "DPZ", name: "Domino's Pizza Inc Common Stock" },
  { symbol: "DRI", name: "Darden Restaurants, Inc." },
  { symbol: "DTE", name: "DTE Energy Company" },
  { symbol: "DUK", name: "Duke Energy Corporation" },
  { symbol: "DVA", name: "DaVita Inc." },
  { symbol: "DVN", name: "Devon Energy Corporation" },
  { symbol: "DXCM", name: "DexCom, Inc. Common Stock" },
  { symbol: "EBAY", name: "eBay Inc. Common Stock" },
  { symbol: "ECHO", name: "EchoStar Corporation Common Stock" },
  { symbol: "ECL", name: "Ecolab, Inc." },
  { symbol: "ED", name: "Consolidated Edison, Inc." },
  { symbol: "EFX", name: "Equifax, Incorporated" },
  { symbol: "EG", name: "Everest Group, Ltd." },
  { symbol: "EIX", name: "Edison International" },
  { symbol: "EL", name: "The Estee Lauder Companies Inc. Class A" },
  { symbol: "ELV", name: "Elevance Health, Inc." },
  { symbol: "EME", name: "EMCOR Group, Inc." },
  { symbol: "EMR", name: "Emerson Electric Co." },
  { symbol: "EOG", name: "EOG Resources, Inc." },
  { symbol: "EQIX", name: "Equinix, Inc. Common Stock REIT" },
  { symbol: "EQR", name: "Equity Residential" },
  { symbol: "EQT", name: "EQT CORP" },
  { symbol: "ERIE", name: "Erie Indemnity Company Class A Common Stock" },
  { symbol: "ES", name: "Eversource Energy" },
  { symbol: "ESS", name: "Essex Property Trust, Inc" },
  { symbol: "ETN", name: "Eaton Corporation, plc Ordinary Shares" },
  { symbol: "ETR", name: "Entergy Corporation" },
  { symbol: "EVRG", name: "Evergy, Inc. Common Stock" },
  { symbol: "EW", name: "Edwards Lifesciences Corp" },
  { symbol: "EXC", name: "Exelon Corporation Common Stock" },
  { symbol: "EXE", name: "Expand Energy Corporation Common Stock" },
  { symbol: "EXPD", name: "Expeditors International of Washington, Inc." },
  { symbol: "EXPE", name: "Expedia Group, Inc. Common Stock" },
  { symbol: "EXR", name: "Extra Space Storage, Inc." },
  { symbol: "F", name: "Ford Motor Company" },
  { symbol: "FANG", name: "Diamondback Energy, Inc. Common Stock" },
  { symbol: "FAST", name: "Fastenal Company Common Stock" },
  { symbol: "FCX", name: "Freeport-McMoran Inc." },
  { symbol: "FDS", name: "Factset Research Systems" },
  { symbol: "FDX", name: "FedEx Corporation" },
  { symbol: "FDXF", name: "FedEx Freight Holding Company, Inc." },
  { symbol: "FE", name: "FirstEnergy Corp." },
  { symbol: "FER", name: "Ferrovial N.V. Ordinary Shares" },
  { symbol: "FERG", name: "Ferguson Enterprises Inc." },
  { symbol: "FFIV", name: "F5, Inc. Common Stock" },
  { symbol: "FICO", name: "Fair Isaac Corporation" },
  { symbol: "FIS", name: "Fidelity National Information Services, Inc." },
  { symbol: "FISV", name: "Fiserv, Inc. Common Stock" },
  { symbol: "FITB", name: "Fifth Third Bancorp" },
  { symbol: "FIX", name: "Comfort Systems USA, Inc." },
  { symbol: "FLEX", name: "Flex Ltd. Ordinary Shares" },
  { symbol: "FOX", name: "Fox Corporation Class B Common Stock" },
  { symbol: "FOXA", name: "Fox Corporation Class A Common Stock" },
  { symbol: "FRT", name: "Federal Realty Investment Trust" },
  { symbol: "FSLR", name: "First Solar, Inc. Common Stock" },
  { symbol: "FTNT", name: "Fortinet, Inc. Common Stock" },
  { symbol: "FTV", name: "Fortive Corporation" },
  { symbol: "GD", name: "General Dynamics Corporation" },
  { symbol: "GDDY", name: "GoDaddy Inc" },
  { symbol: "GE", name: "GE Aerospace" },
  { symbol: "GEHC", name: "GE HealthCare Technologies Inc. Common Stock" },
  { symbol: "GEN", name: "Gen Digital Inc. Common Stock" },
  { symbol: "GEV", name: "GE Vernova Inc." },
  { symbol: "GILD", name: "Gilead Sciences, Inc. Common Stock" },
  { symbol: "GIS", name: "General Mills, Inc." },
  { symbol: "GL", name: "Globe Life Inc." },
  { symbol: "GLW", name: "Corning Incorporated" },
  { symbol: "GM", name: "General Motors Company" },
  { symbol: "GNRC", name: "GENERAC HOLDINGS INC" },
  { symbol: "GOOG", name: "Alphabet Inc. Class C Capital Stock" },
  { symbol: "GOOGL", name: "Alphabet Inc. Class A Common Stock" },
  { symbol: "GPC", name: "Genuine Parts Company" },
  { symbol: "GPN", name: "Global Payments, Inc." },
  { symbol: "GRMN", name: "Garmin Ltd" },
  { symbol: "GS", name: "Goldman Sachs Group Inc." },
  { symbol: "GWW", name: "W.W. Grainger, Inc." },
  { symbol: "HAL", name: "Halliburton Company" },
  { symbol: "HAS", name: "Hasbro, Inc. Common Stock" },
  { symbol: "HBAN", name: "Huntington Bancshares Incorporated Common Stock" },
  { symbol: "HCA", name: "HCA Healthcare, Inc." },
  { symbol: "HD", name: "Home Depot, Inc." },
  { symbol: "HIG", name: "The Hartford Insurance Group, Inc." },
  { symbol: "HII", name: "Huntington Ingalls Industries, Inc." },
  { symbol: "HLT", name: "Hilton Worldwide Holdings Inc." },
  { symbol: "HON", name: "Honeywell International Inc. Common Stock" },
  { symbol: "HONA", name: "Honeywell Aerospace Inc. Common Stock" },
  { symbol: "HOOD", name: "Robinhood Markets, Inc. Class A Common Stock" },
  { symbol: "HPE", name: "Hewlett Packard Enterprise Company" },
  { symbol: "HPQ", name: "HP Inc." },
  { symbol: "HRL", name: "Hormel Foods Corporation" },
  { symbol: "HSIC", name: "Henry Schein, Inc. Common Stock" },
  { symbol: "HST", name: "Host Hotels & Resorts, Inc. Common Stock" },
  { symbol: "HSY", name: "The Hershey Company" },
  { symbol: "HUBB", name: "Hubbell Incorporated" },
  { symbol: "HUM", name: "Humana Inc." },
  { symbol: "HWM", name: "Howmet Aerospace Inc." },
  { symbol: "IBKR", name: "Interactive Brokers Group, Inc. Class A Common Stock" },
  { symbol: "IBM", name: "International Business Machines Corporation" },
  { symbol: "ICE", name: "Intercontinental Exchange  Inc." },
  { symbol: "IDXX", name: "IDEXX Laboratories, Inc. Common Stock" },
  { symbol: "IEX", name: "IDEX Corporation" },
  { symbol: "IFF", name: "International Flavors & Fragrances Inc." },
  { symbol: "INCY", name: "Incyte Corp. Common Stock" },
  { symbol: "INTC", name: "Intel Corporation Common Stock" },
  { symbol: "INTU", name: "Intuit Inc. Common Stock" },
  { symbol: "INVH", name: "Invitation Homes Inc. Common Stock" },
  { symbol: "IP", name: "International Paper Co." },
  { symbol: "IQV", name: "IQVIA Holdings Inc." },
  { symbol: "IR", name: "Ingersoll Rand Inc. Common Stock" },
  { symbol: "IRM", name: "Iron Mountain Inc." },
  { symbol: "ISRG", name: "Intuitive Surgical, Inc. Common Stock" },
  { symbol: "IT", name: "Gartner, Inc." },
  { symbol: "ITW", name: "Illinois Tool Works Inc." },
  { symbol: "IVZ", name: "Invesco LTD" },
  { symbol: "J", name: "Jacobs Solutions Inc." },
  { symbol: "JBHT", name: "J.B. Hunt Transport Services, Inc. Common Stock" },
  { symbol: "JBL", name: "Jabil Inc." },
  { symbol: "JCI", name: "Johnson Controls International plc" },
  { symbol: "JKHY", name: "Jack Henry & Associates, Inc. Common Stock" },
  { symbol: "JNJ", name: "Johnson & Johnson" },
  { symbol: "JPM", name: "JPMorgan Chase & Co." },
  { symbol: "KDP", name: "Keurig Dr Pepper Inc. Common Stock" },
  { symbol: "KEY", name: "KeyCorp" },
  { symbol: "KEYS", name: "Keysight Technologies, Inc." },
  { symbol: "KHC", name: "The Kraft Heinz Company Common Stock" },
  { symbol: "KIM", name: "Kimco Realty Corp." },
  { symbol: "KKR", name: "KKR & Co. Inc." },
  { symbol: "KLAC", name: "KLA Corporation Common Stock" },
  { symbol: "KMB", name: "Kimberly-Clark Corporation Common Stock" },
  { symbol: "KMI", name: "Kinder Morgan, Inc." },
  { symbol: "KO", name: "Coca-Cola Company" },
  { symbol: "KR", name: "The Kroger Co." },
  { symbol: "KVUE", name: "Kenvue Inc." },
  { symbol: "L", name: "Loews Corporation" },
  { symbol: "LDOS", name: "Leidos Holdings, Inc." },
  { symbol: "LEN", name: "Lennar Corporation Class A" },
  { symbol: "LH", name: "Labcorp Holdings Inc." },
  { symbol: "LHX", name: "L3Harris Technologies, Inc." },
  { symbol: "LII", name: "Lennox International Inc." },
  { symbol: "LIN", name: "Linde plc Ordinary Shares" },
  { symbol: "LITE", name: "Lumentum Holdings Inc. Common Stock" },
  { symbol: "LLY", name: "Eli Lilly & Co." },
  { symbol: "LMT", name: "Lockheed Martin Corp." },
  { symbol: "LNT", name: "Alliant Energy Corporation Common Stock" },
  { symbol: "LOW", name: "Lowe's Companies Inc." },
  { symbol: "LRCX", name: "Lam Research Corporation Common Stock" },
  { symbol: "LULU", name: "lululemon athletica inc. Common Stock" },
  { symbol: "LUV", name: "Southwest Airlines Co." },
  { symbol: "LVS", name: "Las Vegas Sands Corp." },
  { symbol: "LYB", name: "LyondellBasell Industries N.V. Class A" },
  { symbol: "LYV", name: "Live Nation Entertainment Inc." },
  { symbol: "MA", name: "Mastercard Incorporated" },
  { symbol: "MAA", name: "Mid-America Apartment Communities, Inc." },
  { symbol: "MAR", name: "Marriott International Class A Common Stock" },
  { symbol: "MAS", name: "Masco Corporation" },
  { symbol: "MCD", name: "McDonald's Corporation" },
  { symbol: "MCHP", name: "Microchip Technology Incorporated Common Stock" },
  { symbol: "MCK", name: "McKesson Corporation" },
  { symbol: "MCO", name: "Moody's Corporation" },
  { symbol: "MDLZ", name: "Mondelez International, Inc. Class A Common Stock" },
  { symbol: "MDT", name: "Medtronic plc" },
  { symbol: "MELI", name: "MercadoLibre, Inc. Common Stock" },
  { symbol: "MET", name: "MetLife, Inc." },
  { symbol: "META", name: "Meta Platforms, Inc. Class A Common Stock" },
  { symbol: "MGM", name: "MGM RESORTS INTERNATIONAL" },
  { symbol: "MKC", name: "McCormick & Company, Incorporated Non-VTG CS" },
  { symbol: "MLM", name: "Martin Marietta Materials" },
  { symbol: "MMM", name: "3M Company" },
  { symbol: "MNST", name: "Monster Beverage Corporation" },
  { symbol: "MO", name: "Altria Group, Inc." },
  { symbol: "MOS", name: "The Mosaic Company" },
  { symbol: "MPC", name: "MARATHON PETROLEUM CORPORATION" },
  { symbol: "MPWR", name: "Monolithic Power Systems, Inc. Common Stock" },
  { symbol: "MRK", name: "Merck & Co., Inc." },
  { symbol: "MRNA", name: "Moderna, Inc. Common Stock" },
  { symbol: "MRSH", name: "Marsh" },
  { symbol: "MRVL", name: "Marvell Technology, Inc. Common Stock" },
  { symbol: "MS", name: "Morgan Stanley" },
  { symbol: "MSCI", name: "MSCI, Inc." },
  { symbol: "MSFT", name: "Microsoft Corporation Common Stock" },
  { symbol: "MSI", name: "Motorola Solutions, Inc. New" },
  { symbol: "MSTR", name: "Strategy Inc Common Stock Class A" },
  { symbol: "MTB", name: "M&T Bank Corp." },
  { symbol: "MTD", name: "Mettler-Toledo International" },
  { symbol: "MU", name: "Micron Technology, Inc. Common Stock" },
  { symbol: "NBIS", name: "Nebius Group N.V. Class A Ordinary Shares" },
  { symbol: "NCLH", name: "Norwegian Cruise Line Holdings Ltd. Ordinary Shares" },
  { symbol: "NDAQ", name: "Nasdaq, Inc. Common Stock" },
  { symbol: "NDSN", name: "Nordson Corporation Common Stock" },
  { symbol: "NEE", name: "NextEra Energy, Inc." },
  { symbol: "NEM", name: "Newmont Corporation" },
  { symbol: "NFLX", name: "Netflix, Inc. Common Stock" },
  { symbol: "NI", name: "NiSource Inc." },
  { symbol: "NKE", name: "Nike, Inc." },
  { symbol: "NOC", name: "Northrop Grumman Corp." },
  { symbol: "NOW", name: "SERVICENOW, INC." },
  { symbol: "NRG", name: "NRG Energy, Inc." },
  { symbol: "NSC", name: "Norfolk Southern Corp." },
  { symbol: "NTAP", name: "NetApp, Inc. Common Stock" },
  { symbol: "NTRS", name: "Northern Trust Corporation Common Stock" },
  { symbol: "NUE", name: "Nucor Corporation" },
  { symbol: "NVDA", name: "NVIDIA Corporation Common Stock" },
  { symbol: "NVR", name: "NVR, Inc." },
  { symbol: "NWS", name: "News Corporation Class B Common Stock" },
  { symbol: "NWSA", name: "News Corporation Class A Common Stock" },
  { symbol: "NXPI", name: "NXP Semiconductors N.V. Common Stock" },
  { symbol: "O", name: "Realty Income Corporation" },
  { symbol: "ODFL", name: "Old Dominion Freight Line, Inc. Common Stock" },
  { symbol: "OKE", name: "Oneok, Inc." },
  { symbol: "OMC", name: "Omnicom Group Inc." },
  { symbol: "ON", name: "ON Semiconductor Corporation Common Stock" },
  { symbol: "ORCL", name: "Oracle Corp" },
  { symbol: "ORLY", name: "O'Reilly Automotive, Inc. Common Stock" },
  { symbol: "OTIS", name: "Otis Worldwide Corporation" },
  { symbol: "OXY", name: "Occidental Petroleum Corporation" },
  { symbol: "PANW", name: "Palo Alto Networks, Inc. Common Stock" },
  { symbol: "PAYX", name: "Paychex, Inc. Common Stock" },
  { symbol: "PCAR", name: "PACCAR Inc. Common Stock" },
  { symbol: "PCG", name: "PG&E Corporation" },
  { symbol: "PDD", name: "PDD Holdings Inc. American Depositary Shares" },
  { symbol: "PEG", name: "Public Service Enterprise Group Incorporated" },
  { symbol: "PEP", name: "PepsiCo, Inc. Common Stock" },
  { symbol: "PFE", name: "Pfizer Inc." },
  { symbol: "PFG", name: "Principal Financial Group Inc Common Stock" },
  { symbol: "PG", name: "Procter & Gamble Company" },
  { symbol: "PGR", name: "Progressive Corporation" },
  { symbol: "PH", name: "Parker-Hannifin Corporation" },
  { symbol: "PHM", name: "Pultegroup, Inc." },
  { symbol: "PKG", name: "Packaging Corp of America" },
  { symbol: "PLD", name: "PROLOGIS, INC." },
  { symbol: "PLTR", name: "Palantir Technologies Inc. Class A Common Stock" },
  { symbol: "PM", name: "Philip Morris International Inc." },
  { symbol: "PNC", name: "PNC Financial Services Group" },
  { symbol: "PNR", name: "Pentair plc" },
  { symbol: "PNW", name: "Pinnacle West Capital Corporation" },
  { symbol: "PODD", name: "Insulet Corporation Common Stock" },
  { symbol: "PPG", name: "PPG Industries, Inc." },
  { symbol: "PPL", name: "PPL Corporation" },
  { symbol: "PRU", name: "Prudential Financial, Inc." },
  { symbol: "PSA", name: "Public Storage" },
  { symbol: "PSKY", name: "Paramount Skydance Corporation Class B Common Stock" },
  { symbol: "PSX", name: "PHILLIPS 66" },
  { symbol: "PTC", name: "PTC Inc. Common Stock" },
  { symbol: "PWR", name: "Quanta Services, Inc." },
  { symbol: "PYPL", name: "PayPal Holdings, Inc. Common Stock" },
  { symbol: "Q", name: "Qnity Electronics, Inc." },
  { symbol: "QCOM", name: "QUALCOMM Incorporated Common Stock" },
  { symbol: "RCL", name: "Royal Caribbean Group" },
  { symbol: "REG", name: "Regency Centers Corporation Common Stock" },
  { symbol: "REGN", name: "Regeneron Pharmaceuticals, Inc. Common Stock" },
  { symbol: "RF", name: "Regions Financial Corp." },
  { symbol: "RJF", name: "Raymond James Financial, Inc." },
  { symbol: "RKLB", name: "Rocket Lab Corporation Common Stock" },
  { symbol: "RL", name: "Ralph Lauren Corporation" },
  { symbol: "RMD", name: "ResMed Inc." },
  { symbol: "ROK", name: "Rockwell Automation, Inc." },
  { symbol: "ROL", name: "Rollins, Inc." },
  { symbol: "ROP", name: "Roper Technologies, Inc. Common Stock" },
  { symbol: "ROST", name: "Ross Stores, Inc. Common Stock" },
  { symbol: "RSG", name: "Republic Services Inc." },
  { symbol: "RTX", name: "RTX Corporation" },
  { symbol: "RVTY", name: "Revvity, Inc." },
  { symbol: "SBAC", name: "SBA Communications Corporation Class A Common Stock" },
  { symbol: "SBUX", name: "Starbucks Corporation Common Stock" },
  { symbol: "SCHW", name: "The Charles Schwab Corporation" },
  { symbol: "SHOP", name: "Shopify Inc. Class A subordinate voting shares" },
  { symbol: "SHW", name: "The Sherwin-Williams Company" },
  { symbol: "SJM", name: "The J.M. Smucker Company" },
  { symbol: "SLB", name: "SLB Limited" },
  { symbol: "SMCI", name: "Super Micro Computer, Inc. Common Stock" },
  { symbol: "SNA", name: "Snap-on Incorporated" },
  { symbol: "SNDK", name: "Sandisk Corporation Common Stock" },
  { symbol: "SNPS", name: "Synopsys, Inc. Common Stock" },
  { symbol: "SO", name: "The Southern Company" },
  { symbol: "SOLV", name: "Solventum Corporation" },
  { symbol: "SPCX", name: "Space Exploration Technologies Corp. Class A Common Stock" },
  { symbol: "SPG", name: "Simon Property Group, Inc." },
  { symbol: "SPGI", name: "S&P Global Inc." },
  { symbol: "SRE", name: "Sempra" },
  { symbol: "STE", name: "STERIS plc" },
  { symbol: "STLD", name: "Steel Dynamics, Inc." },
  { symbol: "STT", name: "State Street Corporation" },
  { symbol: "STX", name: "Seagate Technology Holdings PLC Ordinary Shares (Ireland)" },
  { symbol: "STZ", name: "Constellation Brands, Inc." },
  { symbol: "SW", name: "Smurfit WestRock plc" },
  { symbol: "SWK", name: "Stanley Black & Decker, Inc." },
  { symbol: "SWKS", name: "Skyworks Solutions, Inc. Common Stock" },
  { symbol: "SYF", name: "SYNCHRONY FINANCIAL" },
  { symbol: "SYK", name: "Stryker Corporation" },
  { symbol: "SYY", name: "Sysco Corporation" },
  { symbol: "T", name: "AT&T Inc." },
  { symbol: "TAP", name: "Molson Coors Beverage Company Class B" },
  { symbol: "TDG", name: "TransDigm Group Incorporated" },
  { symbol: "TDY", name: "Teledyne Technologies Incorporated" },
  { symbol: "TECH", name: "Bio-Techne Corp Common Stock" },
  { symbol: "TEL", name: "TE Connectivity plc" },
  { symbol: "TER", name: "Teradyne, Inc. Common Stock" },
  { symbol: "TFC", name: "Truist Financial Corporation" },
  { symbol: "TGT", name: "Target Corporation" },
  { symbol: "TJX", name: "TJX Companies, Inc. (The)" },
  { symbol: "TKO", name: "TKO Group Holdings, Inc." },
  { symbol: "TMO", name: "Thermo Fisher Scientific, Inc." },
  { symbol: "TMUS", name: "T-Mobile US, Inc. Common Stock" },
  { symbol: "TPL", name: "Texas Pacific Land Corporation" },
  { symbol: "TPR", name: "Tapestry, Inc. Common Stock" },
  { symbol: "TRGP", name: "Targa Resources Corp." },
  { symbol: "TRI", name: "Thomson Reuters Corporation Common Shares" },
  { symbol: "TRMB", name: "Trimble Inc. Common Stock" },
  { symbol: "TROW", name: "T. Rowe Price Group, Inc. Common Stock" },
  { symbol: "TRV", name: "The Travelers Companies, Inc." },
  { symbol: "TSCO", name: "Tractor Supply Company Common Stock" },
  { symbol: "TSLA", name: "Tesla, Inc. Common Stock" },
  { symbol: "TSN", name: "Tyson Foods, Inc." },
  { symbol: "TT", name: "Trane Technologies plc" },
  { symbol: "TTD", name: "The Trade Desk, Inc. Class A Common Stock" },
  { symbol: "TTWO", name: "Take-Two Interactive Software, Inc. Common Stock" },
  { symbol: "TXN", name: "Texas Instruments Incorporated Common Stock" },
  { symbol: "TXT", name: "Textron, Inc." },
  { symbol: "TYL", name: "Tyler Technologies, Inc." },
  { symbol: "UAL", name: "United Airlines Holdings, Inc. Common Stock" },
  { symbol: "UBER", name: "Uber Technologies, Inc." },
  { symbol: "UDR", name: "UDR, Inc." },
  { symbol: "UHS", name: "Universal Health Services, Inc. Class B" },
  { symbol: "ULTA", name: "Ulta Beauty, Inc. Common Stock" },
  { symbol: "UNH", name: "UNITEDHEALTH GROUP INCORPORATED (Delaware)" },
  { symbol: "UNP", name: "Union Pacific Corp." },
  { symbol: "UPS", name: "United Parcel Service, Inc. Class B" },
  { symbol: "URI", name: "United Rentals, Inc." },
  { symbol: "USB", name: "U.S. Bancorp" },
  { symbol: "V", name: "VISA Inc." },
  { symbol: "VEEV", name: "Veeva Systems Inc." },
  { symbol: "VICI", name: "VICI Properties Inc. Common Stock" },
  { symbol: "VLO", name: "Valero Energy Corporation" },
  { symbol: "VLTO", name: "Veralto Corporation" },
  { symbol: "VMC", name: "Vulcan Materials Company(Holding Company)" },
  { symbol: "VRSK", name: "Verisk Analytics, Inc. Common Stock" },
  { symbol: "VRSN", name: "VeriSign, Inc. Common Stock" },
  { symbol: "VRT", name: "Vertiv Holdings Co Class A Common Stock" },
  { symbol: "VRTX", name: "Vertex Pharmaceuticals Incorporated Common Stock" },
  { symbol: "VST", name: "Vistra Corp." },
  { symbol: "VTR", name: "Ventas, Inc." },
  { symbol: "VTRS", name: "Viatris Inc. Common Stock" },
  { symbol: "VZ", name: "Verizon Communications" },
  { symbol: "WAB", name: "Wabtec Inc." },
  { symbol: "WAT", name: "Waters Corp" },
  { symbol: "WBD", name: "Warner Bros. Discovery, Inc. Series A Common Stock" },
  { symbol: "WDAY", name: "Workday, Inc. Class A Common Stock" },
  { symbol: "WDC", name: "Western Digital Corporation Common Stock" },
  { symbol: "WEC", name: "WEC Energy Group, Inc." },
  { symbol: "WELL", name: "Welltower Inc." },
  { symbol: "WFC", name: "Wells Fargo & Co." },
  { symbol: "WM", name: "Waste Management, Inc." },
  { symbol: "WMB", name: "Williams Companies Inc." },
  { symbol: "WMT", name: "Walmart Inc. Common Stock" },
  { symbol: "WRB", name: "W.R. Berkley Corporation" },
  { symbol: "WSM", name: "Williams-Sonoma, Inc." },
  { symbol: "WST", name: "West Pharmaceutical Services, Inc." },
  { symbol: "WTW", name: "Willis Towers Watson Public Limited Company Ordinary Shares" },
  { symbol: "WY", name: "Weyerhaeuser Company" },
  { symbol: "WYNN", name: "Wynn Resorts, Limited Common stock" },
  { symbol: "XEL", name: "Xcel Energy Inc. Common Stock" },
  { symbol: "XOM", name: "ExxonMobil Holdings Corporation" },
  { symbol: "XYL", name: "Xylem Inc" },
  { symbol: "XYZ", name: "Block, Inc." },
  { symbol: "YUM", name: "Yum! Brands, Inc." },
  { symbol: "ZBH", name: "Zimmer Biomet Holdings, Inc." },
  { symbol: "ZBRA", name: "Zebra Technologies Corporation Class A Common Stock" },
  { symbol: "ZTS", name: "ZOETIS INC." },
];

export const BOT_WATCHLIST_SYMBOLS: readonly string[] = BOT_WATCHLIST.map((entry) => entry.symbol);
